# TODO(#1706): Remove CL2_ENABLE_IMMUTABLE_SECRETS_AND_CONFIGMAPS usage when support for 1.17 is dropped.
{{$EnableImmutableSecretsAndConfigmaps := DefaultParam .CL2_ENABLE_IMMUTABLE_SECRETS_AND_CONFIGMAPS true}}

apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}
{{if and $EnableImmutableSecretsAndConfigmaps (not (eq (Mod .Index 20) 10 19)) }}
immutable: true
{{end}}
type: Opaque
data:
  password: c2NhbGFiaWxpdHkK
